apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackupSchedule
metadata:
  name: abs-jen
  namespace: kube-system
spec:
  schedulePolicyName: sp-demo
  template:
    spec:
      backupLocation: bl-demo
      namespaces:
      - jen
      reclaimPolicy: Delete