apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackupSchedule
metadata:
  name: abs-demo
  namespace: kube-system
spec:
  schedulePolicyName: sp-demo
  template:
    spec:
      backupLocation: bl-demo
      namespaces:
      #- mysql
      #- mongodb
      - default # not recommended to use default, use a named namespace instead. To add more, edit the object on the fly
      reclaimPolicy: Delete