apiVersion: stork.libopenstorage.org/v1alpha1
kind: BackupLocation
metadata:
  name: bl-demo
  namespace: kube-system
  annotations:
    stork.libopenstorage.org/skipresource: "true"
location:
  type: google
  path: "bucket-demo-gpx"
  googleConfig:
    projectID: "gcproject-test"
    accountKey: >-
      {
        #SA.JSON_Info_Here
      }

