#! /bin/bash
echo 'Hi friend, '

# gcloud compute disks list | grep 'px-do-not'
# gcloud compute disks list --filter="region:(us-central)"  | grep 'px-do-not'

## Personal env:
echo "I've found the following PX disk & size..."
gcloud compute disks list --filter="name~'px-do*'" | grep standard | awk '{print $1,$4}'
echo -e "\n"


LIST=$(gcloud compute disks list --filter="name~'px-do*'" | grep standard | cut -d " " -f 1)

#NEW_SIZE=5TB
NEW_SIZE="40GB"
REG="us-central1"

echo "Ok, lets resize...to $NEW_SIZE"
for disk in ${LIST}
do
     gcloud compute disks resize "$disk" --region=$REG --size=$NEW_SIZE
     #sleep 20
done


echo "Here is the updated PX disk & size..."
gcloud compute disks list --filter="name~'px-do*'" | grep standard | awk '{print $1,$4}'



