apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-claim
  namespace: jen
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: jenk-primary-snapshot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 10Gi
